In [1]:
import pandas as pd
import numpy as np
from sklearn import tree 

from sklearn.neural_network import MLPClassifier 
from sklearn.naive_bayes import GaussianNB 



from sklearn.model_selection import train_test_split

import sklearn.metrics as metrics

In [32]:
file_path='./datas/'
file_name=file_path+"h1b_dev_preprocessing.csv"
df=pd.read_csv(file_name,keep_default_na=False)
df.columns

Index(['CASE_STATUS', 'FULL_TIME_POSITION', 'YEAR', 'SOC_CODE', 'STATE',
       'WAGE_CATEGORY'],
      dtype='object')

In [3]:
df_denied = df[df['CASE_STATUS'] == 1] #1 = DiNED

In [4]:
df_certified = df[df['CASE_STATUS'] == 0] #1 = CERTIFIED

In [33]:
df["CASE_STATUS"].value_counts()

0    522654
1     18868
Name: CASE_STATUS, dtype: int64

In [5]:
Input_Certified, Input_Certified_extra, y_certified, y_certified_extra = train_test_split(df[df.CASE_STATUS == 0],
                                                                                          df_certified.CASE_STATUS, train_size= 0.06, random_state=1)

c:\users\adboy\appdata\local\programs\python\python36\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [6]:
df_train=Input_Certified.append(df_denied)

In [7]:
df_train.CASE_STATUS.value_counts()

0    31359
1    18868
Name: CASE_STATUS, dtype: int64

In [8]:
df_train=pd.get_dummies(df_train,columns=['YEAR', 'SOC_CODE', 'STATE',
       'WAGE_CATEGORY'])

In [20]:
df_train

CASE_STATUS  FULL_TIME_POSITION  YEAR_2011  YEAR_2012  YEAR_2013  \
129550            0                   1          0          0          0   
475593            0                   1          0          0          0   
433344            0                   1          0          0          1   
134762            0                   1          0          0          0   
423550            0                   1          1          0          0   
70106             0                   1          0          0          0   
154318            0                   1          0          0          0   
84516             0                   0          0          0          0   
260975            0                   1          0          0          0   
285482            0                   1          0          0          1   
441252            0                   1          1          0          0   
226942            0                   1          1          0          0   
366923            0                   1          0          0          1   
122218            0                   0          0          0          0   
498972            0                   1          0          1          0   
121746            0                   0          0          0          0   
162078            0                   1          0          0          0   
277667            0                   1          0          0          0   
246133            0                   1          0          0          1   
343980            0                   0          0          0          0   
110693            0                   1          0          1          0   
173632            0                   0          0          1          0   
241466            0                   1          0          0          0   
216780            0                   1          0          0          0   
287851            0                   1          0          0          1   
309593            0                   1          0          0          0   
32779             0                   1          0          1          0   
310965            0                   1          0          0          1   
456109            0                   1          0          0          0   
67521             0                   1          0          0          1   
...             ...                 ...        ...        ...        ...   
540887            1                   1          0          0          0   
540895            1                   1          1          0          0   
540934            1                   1          0          0          0   
540965            1                   1          0          0          0   
540986            1                   1          0          0          0   
540993            1                   1          0          0          0   
540994            1                   1          1          0          0   
541033            1                   1          0          0          0   
541039            1                   1          1          0          0   
541061            1                   1          0          1          0   
541064            1                   0          0          0          0   
541076            1                   1          0          0          0   
541119            1                   1          1          0          0   
541149            1                   1          1          0          0   
541196            1                   1          0          1          0   
541203            1                   1          0          0          1   
541224            1                   1          1          0          0   
541234            1                   0          0          0          0   
541245            1                   1          0          0          1   
541277            1                   1          1          0          0   
541308            1                   1          0      

In [11]:
X = df_train.drop('CASE_STATUS', axis=1)
y = df_train.CASE_STATUS
test_size = 0.20
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=1)
X_train.columns

Index(['FULL_TIME_POSITION', 'YEAR_2011', 'YEAR_2012', 'YEAR_2013',
       'YEAR_2014', 'YEAR_2015', 'YEAR_2016', 'SOC_CODE_0o0',
       'SOC_CODE_0o1001', 'SOC_CODE_0o1002',
       ...
       'STATE_WASHINGTON', 'STATE_WISCONSIN', 'STATE_WYOMING', 'STATE_YORK',
       'WAGE_CATEGORY_HIGH', 'WAGE_CATEGORY_LOW', 'WAGE_CATEGORY_MEDIUM',
       'WAGE_CATEGORY_NON', 'WAGE_CATEGORY_VERY HIGH',
       'WAGE_CATEGORY_VERY LOW'],
      dtype='object', length=111)

In [12]:
df_train['CASE_STATUS'].value_counts()

0    31359
1    18868
Name: CASE_STATUS, dtype: int64

In [13]:
dtree = tree.DecisionTreeClassifier()
dtree = dtree.fit(X_train, y_train) 

In [14]:
y_pred = dtree.predict(X_test)
y_prob = dtree.predict_proba(X_test)

In [22]:
print("test", y_test[:10])
print("pred", y_pred[:10])
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test, y_pred))

test 319077    0
357468    1
396136    1
275003    0
443858    0
470346    1
354884    0
387583    0
95486     0
2376      0
Name: CASE_STATUS, dtype: int64
pred [0 0 0 0 0 1 1 0 0 0]
[[5334  962]
 [2131 1619]]
             precision    recall  f1-score   support

          0       0.71      0.85      0.78      6296
          1       0.63      0.43      0.51      3750

avg / total       0.68      0.69      0.68     10046



In [16]:
mlp = MLPClassifier(hidden_layer_sizes=(20,20,20,20,20), max_iter=1000)
mlp.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(20, 20, 20, 20, 20), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [23]:
y_pred_mlp = mlp.predict(X_test)
confusion = metrics.confusion_matrix(y_test, y_pred_mlp)
print(confusion)
print(metrics.classification_report(y_test, y_pred_mlp))

[[5338  958]
 [1952 1798]]
             precision    recall  f1-score   support

          0       0.73      0.85      0.79      6296
          1       0.65      0.48      0.55      3750

avg / total       0.70      0.71      0.70     10046



In [18]:
gaus_clf = GaussianNB()
gaus_clf.fit(X_train, y_train)

GaussianNB(priors=None)

In [19]:
y_pred_glb = gaus_clf.predict(X_test)
confusion = metrics.confusion_matrix(y_test, y_pred_glb)
print(confusion)
print(metrics.classification_report(y_test, y_pred_glb))

[[6013  283]
 [3266  484]]
             precision    recall  f1-score   support

          0       0.65      0.96      0.77      6296
          1       0.63      0.13      0.21      3750

avg / total       0.64      0.65      0.56     10046



In [21]:
import pickle

In [31]:
save_dtree=file_path+'DTREE_Model_h1b.sav'
pickle.dump(dtree, open(save_dtree, 'wb'))

In [29]:
save_mlp=file_path+'MLP_Model_h1b.sav'
pickle.dump(dtree, open(save_mlp, 'wb'))

In [30]:
save_gaus=file_path+'GAUS_Model_h1b.sav'
pickle.dump(dtree, open(save_gaus, 'wb'))