In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path='./datas/'
file_name=file_path+"h1b_train_preprocessing.csv"
df=pd.read_csv(file_name,keep_default_na=False)
#df.columns
print("DATA LOAD DONE")

DATA LOAD DONE


In [157]:
df["ID"]=df.index

In [163]:
df["ID"]=str(df["ID"].values)+"1"

In [164]:
df

CASE_STATUS  FULL_TIME_POSITION  YEAR SOC_CODE          STATE  \
0                  0                   1  2014   0o1400     CALIFORNIA   
1                  0                   1  2015   0o1400     CALIFORNIA   
2                  0                   1  2014   0o1400     CALIFORNIA   
3                  0                   1  2011      0o0       ILLINOIS   
4                  1                   1  2015   0o1300     CALIFORNIA   
5                  0                   1  2011   0o1404     CALIFORNIA   
6                  0                   0  2016   0o1200       CAROLINA   
7                  0                   1  2012   0o1400           OHIO   
8                  0                   1  2011   0o1404       VIRGINIA   
9                  0                   1  2014   0o1400     CALIFORNIA   
10                 0                   1  2013   0o1400     WASHINGTON   
11                 0                   1  2012   0o1400     CALIFORNIA   
12                 0                   1  2014   0o1004          TEXAS   
13                 0                   1  2013   0o1400         JERSEY   
14                 0                   1  2011   0o1004      MINNESOTA   
15                 0                   1  2014   0o1402     CALIFORNIA   
16                 0                   1  2015   0o1240          TEXAS   
17                 0                   1  2011   0o1430       MARYLAND   
18                 0                   1  2014   0o1400          TEXAS   
19                 0                   1  2016   0o1400     CALIFORNIA   
20                 0                   1  2013   0o1400     WASHINGTON   
21                 0                   1  2012   0o1400        FLORIDA   
22                 0                   1  2015   0o1400     CALIFORNIA   
23                 0                   0  2016   0o1010          TEXAS   
24                 0                   1  2013   0o1004           YORK   
25                 0                   1  2013   0o1012           YORK   
26                 0                   1  2011   0o1400  MASSACHUSETTS   
27                 1                   1  2015   0o1404     CALIFORNIA   
28                 0                   1  2012   0o1200   PENNSYLVANIA   
29                 0                   1  2014   0o1400   PENNSYLVANIA   
...              ...                 ...   ...      ...            ...   
1626857            0                   1  2014   0o1021     CALIFORNIA   
1626858            0                   1  2014   0o1002        GEORGIA   
1626859            0                   1  2012   0o1400         JERSEY   
1626860            0                   1  2015   0o1400           RICO   
1626861            0                   1  2016   0o1400     WASHINGTON   
1626862            0                   1  2014   0o1400          TEXAS   
1626863            0                   1  2012   0o1400  MASSACHUSETTS   
1626864            0                   1  2014   0o1100         KANSAS   
1626865            0                   1  2011   0o1040       CAROLINA   
1626866            0                   1  2015   0o1400     CALIFORNIA   
1626867            0                   1  2014   0o1400       DELAWARE   
1626868            0                   0  2016   0o1400     CALIFORNIA   
1626869            0                   1  2014   0o1400           OHIO   
1626870            0                   1  2011   0o1100           UTAH   
1626871            0                   1  2016   0o1014           YORK   
1626872            1                   0  2016   0o1010       CAROLINA   
1626873            0                   0  2016   0o1400         JERSEY   
1626874            0                   1  2012   0o1400       COLUMBIA   
1626875            0                   1  2012   0o1424       CAROLINA   
1626876            0                   0  2016   0o1021     CALIFORNIA   
1626877            0                   0  2016   0o1404      MINNESOTA   
1626878            0                   1  2016   0o1400       MARYLAND   
1626879      

In [37]:
import itertools

In [87]:
 x=[]

num=0o0
list_=np.array([0o0,0o400,0o200,0o100,0o040,0o020,0o010,0o04,0o02,0o01])
for i in range (0,len(list_)) :
    num=0o0
    num+=list_[i]
    x.append((np.array(list(itertools.combinations(list_,i)))))
    print((np.array(list(itertools.combinations(list_,i)))))
    print(oct(int(num)))
    #print (oct(int(0o400/0o010)))

x

[]
0o0
[[  0]
 [256]
 [128]
 [ 64]
 [ 32]
 [ 16]
 [  8]
 [  4]
 [  2]
 [  1]]
0o400
[[  0 256]
 [  0 128]
 [  0  64]
 [  0  32]
 [  0  16]
 [  0   8]
 [  0   4]
 [  0   2]
 [  0   1]
 [256 128]
 [256  64]
 [256  32]
 [256  16]
 [256   8]
 [256   4]
 [256   2]
 [256   1]
 [128  64]
 [128  32]
 [128  16]
 [128   8]
 [128   4]
 [128   2]
 [128   1]
 [ 64  32]
 [ 64  16]
 [ 64   8]
 [ 64   4]
 [ 64   2]
 [ 64   1]
 [ 32  16]
 [ 32   8]
 [ 32   4]
 [ 32   2]
 [ 32   1]
 [ 16   8]
 [ 16   4]
 [ 16   2]
 [ 16   1]
 [  8   4]
 [  8   2]
 [  8   1]
 [  4   2]
 [  4   1]
 [  2   1]]
0o200
[[  0 256 128]
 [  0 256  64]
 [  0 256  32]
 [  0 256  16]
 [  0 256   8]
 [  0 256   4]
 [  0 256   2]
 [  0 256   1]
 [  0 128  64]
 [  0 128  32]
 [  0 128  16]
 [  0 128   8]
 [  0 128   4]
 [  0 128   2]
 [  0 128   1]
 [  0  64  32]
 [  0  64  16]
 [  0  64   8]
 [  0  64   4]
 [  0  64   2]
 [  0  64   1]
 [  0  32  16]
 [  0  32   8]
 [  0  32   4]
 [  0  32   2]
 [  0  32   1]
 [  0  16   8]
 [  0  16

[array([], shape=(1, 0), dtype=float64), array([[  0],
        [256],
        [128],
        [ 64],
        [ 32],
        [ 16],
        [  8],
        [  4],
        [  2],
        [  1]]), array([[  0, 256],
        [  0, 128],
        [  0,  64],
        [  0,  32],
        [  0,  16],
        [  0,   8],
        [  0,   4],
        [  0,   2],
        [  0,   1],
        [256, 128],
        [256,  64],
        [256,  32],
        [256,  16],
        [256,   8],
        [256,   4],
        [256,   2],
        [256,   1],
        [128,  64],
        [128,  32],
        [128,  16],
        [128,   8],
        [128,   4],
        [128,   2],
        [128,   1],
        [ 64,  32],
        [ 64,  16],
        [ 64,   8],
        [ 64,   4],
        [ 64,   2],
        [ 64,   1],
        [ 32,  16],
        [ 32,   8],
        [ 32,   4],
        [ 32,   2],
        [ 32,   1],
        [ 16,   8],
        [ 16,   4],
        [ 16,   2],
        [ 16,   1],
        [  8,   4],
        [

In [65]:
oct(sum(x[1][3]))

'0o100'

In [89]:
x=np.array(x)

In [92]:
len(x)

10

In [91]:
x.flatten()

array([array([], shape=(1, 0), dtype=float64),
       array([[  0],
       [256],
       [128],
       [ 64],
       [ 32],
       [ 16],
       [  8],
       [  4],
       [  2],
       [  1]]),
       array([[  0, 256],
       [  0, 128],
       [  0,  64],
       [  0,  32],
       [  0,  16],
       [  0,   8],
       [  0,   4],
       [  0,   2],
       [  0,   1],
       [256, 128],
       [256,  64],
       [256,  32],
       [256,  16],
       [256,   8],
       [256,   4],
       [256,   2],
       [256,   1],
       [128,  64],
       [128,  32],
       [128,  16],
       [128,   8],
       [128,   4],
       [128,   2],
       [128,   1],
       [ 64,  32],
       [ 64,  16],
       [ 64,   8],
       [ 64,   4],
       [ 64,   2],
       [ 64,   1],
       [ 32,  16],
       [ 32,   8],
       [ 32,   4],
       [ 32,   2],
       [ 32,   1],
       [ 16,   8],
       [ 16,   4],
       [ 16,   2],
       [ 16,   1],
       [  8,   4],
       [  8,   2],
       [  8,   1],

In [113]:
temp10=[]
for i in range(0,len(x)) :
    for j in range(0,len(x[i])):
        temp10.append(oct(sum(x[i][j])))
temp9=np.array(temp10)

In [117]:
np.unique(temp9)

array(['0o0', '0o1', '0o10', '0o100', '0o101', '0o102', '0o103', '0o104',
       '0o105', '0o106', '0o107', '0o11', '0o110', '0o111', '0o112',
       '0o113', '0o114', '0o115', '0o116', '0o117', '0o12', '0o120',
       '0o121', '0o122', '0o123', '0o124', '0o125', '0o126', '0o127',
       '0o13', '0o130', '0o131', '0o132', '0o133', '0o134', '0o135',
       '0o136', '0o137', '0o14', '0o140', '0o141', '0o142', '0o143',
       '0o144', '0o145', '0o146', '0o147', '0o15', '0o150', '0o151',
       '0o152', '0o153', '0o154', '0o155', '0o156', '0o157', '0o16',
       '0o160', '0o161', '0o162', '0o163', '0o164', '0o165', '0o166',
       '0o167', '0o17', '0o170', '0o171', '0o172', '0o173', '0o174',
       '0o175', '0o176', '0o177', '0o2', '0o20', '0o200', '0o201',
       '0o202', '0o203', '0o204', '0o205', '0o206', '0o207', '0o21',
       '0o210', '0o211', '0o212', '0o213', '0o214', '0o215', '0o216',
       '0o217', '0o22', '0o220', '0o221', '0o222', '0o223', '0o224',
       '0o225', '0o226', '0o

In [111]:
temp2=pd.read_csv('./datas/h1b_train_ratio.csv',keep_default_na=False)
temp3=pd.read_csv('./datas/soccode_with_ratio.csv',keep_default_na=False)

In [112]:
temp2

STATE  CERTIFIED  DENIED     ratio
0              ALABAMA       5083     325  0.063939
1               ALASKA        631      94  0.148970
2              ARIZONA      22412     698  0.031144
3             ARKANSAS       7973     194  0.024332
4           CALIFORNIA     289956   10610  0.036592
5             COLORADO      16358     658  0.040225
6          CONNECTICUT      26919     746  0.027713
7             DELAWARE       9581     217  0.022649
8   DISTRICTOFCOLUMBIA      11513     709  0.061583
9              FLORIDA      55029    3283  0.059659
10             GEORGIA      55035    1676  0.030453
11              HAWAII       1819     227  0.124794
12               IDAHO       2067     103  0.049831
13            ILLINOIS      85084    2353  0.027655
14             INDIANA      15522     505  0.032534
15                IOWA       8732     272  0.031150
16              KANSAS       7207     259  0.035937
17            KENTUCKY       6757     255  0.037739
18           LOUISIANA       5821     365  0.062704
19               MAINE       2127      67  0.031500
20            MARYLAND      28839    1260  0.043691
21       MASSACHUSETTS      60350    2159  0.035775
22            MICHIGAN      43561    1317  0.030233
23           MINNESOTA      26406     675  0.025562
24         MISSISSIPPI       2148     174  0.081006
25            MISSOURI      18085     485  0.026818
26             MONTANA        468      46  0.098291
27            NEBRASKA       4741     163  0.034381
28              NEVADA       3612     372  0.102990
29        NEWHAMPSHIRE       5155     132  0.025606
30           NEWJERSEY     114636    2931  0.025568
31           NEWMEXICO       2809     207  0.073692
32             NEWYORK     150308    7655  0.050929
33       NORTHCAROLINA      42737    1136  0.026581
34         NORTHDAKOTA       1494      76  0.050870
35                OHIO      41232    1160  0.028133
36            OKLAHOMA       5461     286  0.052371
37              OREGON      12569     366  0.029119
38        PENNSYLVANIA      58654    1666  0.028404
39          PUERTORICO        698     135  0.193410
40         RHODEISLAND       6376     151  0.023683
41       SOUTHCAROLINA       6619     321  0.048497
42         SOUTHDAKOTA        999      51  0.051051
43           TENNESSEE      14379     492  0.034217
44               TEXAS     152661    5111  0.033479
45                UTAH       6785     364  0.053648
46             VERMONT        988      62  0.062753
47            VIRGINIA      47191    1719  0.036426
48          WASHINGTON      53748    1222  0.022736
49        WESTVIRGINIA       1470      97  0.065986
50           WISCONSIN      17550     441  0.025128
51             WYOMING        369      60  0.162602

In [127]:
temp3.sort_values('ratio_soc')

Unnamed: 0 SOC_CODE  ratio_soc
3            3   0o1003   0.000000
5            5   0o1005   0.000000
8            8   0o1021   0.000000
17          17   0o1110   0.000000
29          29   0o1403   0.000000
27          27   0o1400   0.018209
36          36   0o1514   0.028350
24          24   0o1300   0.031334
18          18   0o1120   0.032944
13          13   0o1044   0.034114
28          28   0o1402   0.034884
23          23   0o1240   0.035714
14          14   0o1050   0.035727
30          30   0o1404   0.037085
15          15   0o1100   0.038878
33          33   0o1424   0.039106
35          35   0o1440   0.040961
11          11   0o1030   0.045211
37          37   0o1520   0.045455
19          19   0o1140   0.048218
7            7   0o1020   0.049732
4            4   0o1004   0.053905
25          25   0o1304   0.062125
2            2   0o1002   0.063996
20          20   0o1200   0.070015
21          21   0o1204   0.070748
16          16   0o1104   0.073351
26          26   0o1340   0.078313
12          12   0o1040   0.078756
32          32   0o1422   0.079724
6            6   0o1010   0.086915
0            0      0o0   0.101452
34          34   0o1430   0.105698
31          31   0o1420   0.117162
39          39   0o1620   0.120215
38          38   0o1600   0.173913
10          10   0o1024   0.204819
1            1   0o1001   0.240000
9            9   0o1022   0.287081
22          22   0o1220   0.500000

In [118]:
tx=[0o0400,0o020,0o010]

In [126]:
(tx.sort(reverse=True))[0]

TypeError: 'NoneType' object is not subscriptable

In [124]:
tx

[256, 16, 8]

In [165]:
x=[]


In [166]:
len(x)

0